### PR TITLE
Add a simple logging area/task runner

### PR DESCRIPTION
**Pull request by alexgleith**
Very simple. Just logs things. Doesn't handle errors.

### CODE REVIEW

**Comment by alexgleith** [comment]
Closes #9

**Comment by jessjaco** [comment]
I'm concerned this doesn't support the `send_area_to_processor` arg of `Processor`

**Comment by alexgleith** [comment]
> I'm concerned this doesn't support the send_area_to_processor arg of Processor

I can add that in. I don't know why it's there is all.

Will add it now.

**Comment by jessjaco** [comment]
It's there because I use the area in a lot of the processors I write and use. But I don't want to make every processor support an area argument. It does stick out a little, but it's the best option I could come up with.

**Pull request merged**
