### PR TITLE
Change S-2 processor to have harmonize_to_old option

### PR DESCRIPTION
**Pull request by alexgleith**
Tweaked the `harmonize_to_old` function so that it handles data without the band dimension.

Changed the `s-2` processor so that there are two flags, one for `scale_and_offset` and another for `harmonize_to_old`.

Array histogram before:

image

And after:

image

### CODE REVIEW

**Comment by alexgleith** [comment]
Any issues with me merging this, @jessjaco?

**Comment by jessjaco** [comment]
1. I'd prefer making changes to the develop branch if possible. I don't have the bandwidth to track changes across multiple branches.
2. I'm concerned about the change to SimpleLoggingAreaTask. I don't currently use it but it is limiting processing to datasets that have a time variable. What about doing this step in the processor?
3. I think I follow the changes in the harmonization - they're to handle datasets? I'd probably just cast to / from a dataset and recast at the end so there's not duplicate logic

**Comment by alexgleith** [comment]
>I'd prefer making changes to the develop branch if possible. I don't have the bandwidth 

I don't want to work of the `develop` branch yet, as I already have code that works off the `main` branch. Will refactor, but don't want to yet. I'd prefer to get this merged into `main` and for us to handle the changes from `develop` separately. I too don't want to track changes in multiple branches!

> I'm concerned about the change to SimpleLoggingAreaTask.

Yeah, good point. I'll have a look at how to incorporate that into the processor.

> I'd probably just cast to / from a dataset and recast at the end so there's not duplicate logic

I guess so... I'll look at that too.

**Comment by alexgleith** [comment]
I think this resolves concerns 2 and 3, @jessjaco.

Can we compromise on 1 please?

**Pull request merged**
